repos:
-   repo: https://github.com/psf/black
    rev: '19.10b0'
    hooks:
    - id: black
-   repo: local
    hooks:
        - id: mypy
          name: mypy
          entry: mypy
          language: system
          types: [python]
          files: pyartifactory/
-   repo: https://github.com/Yelp/detect-secrets
    rev: 'v0.13.0'
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
-   repo: https://github.com/PyCQA/bandit
    rev: '1.6.2'
    hooks:
    - id: bandit
      args: ['--exclude', 'tests/*,venv,.venv']
-   repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.0
    hooks:
    -   id: markdown-toc
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        files: pyartifactory/
